name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 6:00 of UTF+8 every day
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  test-nightly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.12-dev" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: deadsnakes/action@v3.0.1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Unit tests
        run: nox -s tests_venv_current
