name: Build and Upload Python Package

on:
  release:
    types: [ published ]

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - name: Install nox
        run: python -m pip install nox
      - name: Build sdist
        run: nox -s build_sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/*.tar.gz
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/*.whl
  publish:
    name: Publish
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload wheels to Github release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo }, sha } = context;
            
            // GITHUB_REF would be refs/tags/<tag_name>
            const tag = process.env.GITHUB_REF.split("/").pop();

            console.log('environment', process.versions);
            console.log({ owner, repo, sha });

            const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag });

            console.log('get release', { release });

            for (let file of await fs.readdir('dist')) {
              console.log('uploading', file);
              await github.rest.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./dist/${file}`)
              });
            }

      - name: Publish package to PyPI
        # Upload to PyPI for a stable release
        if: ${{ github.event.release.prerelease == false }}
        env:
          IS_DEV: ${{ github.repository_owner != 'alibaba' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # env is a string
          repository_url: ${{ env.IS_DEV == 'true' && 'https://test.pypi.org/legacy/' || '' }}
          skip_existing: ${{ env.IS_DEV }}
          verbose: ${{ env.IS_DEV }}
